### ISSUE TITLE
V0.0.3 not workig

### ISSUE THREAD

**Issue by GigiPompieru** [floringhimie/salusfy#17]
The new update broke the thermostat for me. Is this generic?

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:360
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:21:17 (1 occurrences)
Last logged: 16:21:17
Error while setting up salusfy platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/salusfy/climate.py", line 78, in async_setup_platform
    await async_setup_reload_service(hass, DOMAIN, PLATFORMS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'async_setup_reload_service' is not defined
```

_Originally posted by @GigiPompieru in https://github.com/floringhimie/salusfy/issues/15#issuecomment-1883157033_

**Comment by Claudio1L** [comment]
same for me:
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:361
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 15:32:55 (1 occurrences)
Last logged: 15:32:55
Error while setting up salusfy platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/salusfy/climate.py", line 78, in async_setup_platform
    await async_setup_reload_service(hass, DOMAIN, PLATFORMS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'async_setup_reload_service' is not defined

**Comment by GigiPompieru** [comment]
> i don't use last version, but seems to me that line 38 needs to be uncommented..

this fixed it.

What I have noticed is that it pulls the data slower than the old version.
I have 2 zones for my IT500, the second being an IT300, and the zone 2 gets the data 30 seconds before zone 1 after the restart.

**Comment by GigiPompieru** [comment]
The thermostat works after the initial errors. It sets the temperature in cloud and also reads any modifications you do in the salus app without any more errors.

Its very strange.

**Comment by Claudio1L** [comment]
I went back to 0.0.1 and manually applied https://github.com/floringhimie/salusfy/pull/16  . Works fine and errors disappeared. @aver-ua  https://github.com/floringhimie/salusfy/pull/11 broke something.

**Comment by GigiPompieru** [comment]
> I went back to 0.0.1 and manually applied #16 . Works fine and errors disappeared. @aver-ua #11 broke something.

including the network errors?

**Comment by aver-ua** [comment]
> I went back to 0.0.1 and manually applied #16 . Works fine and errors disappeared. @aver-ua #11 broke something.

yes, pull request #11 produces warnings and errors in HA log, but the component works
so, i use `climate.py` without #11

**Comment by Claudio1L** [comment]
Confirmed, seems ok without https://github.com/floringhimie/salusfy/pull/11  Now the problem is that the update hacs is proposing includes https://github.com/floringhimie/salusfy/pull/11 doesn't it?

**Comment by GigiPompieru** [comment]
maybe create #17 with the final code that works without errors?
