### ISSUE TITLE
Failed to restart Home Assistant - 

### ISSUE THREAD

**Issue by Nortag82** [floringhimie/salusfy#6]
Followed the steps, but when trying to restart system, getting this:

Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Platform error climate.salusfy - No module named 'custom_components.salusfy.climate'

Sorry, very new to HA.

Log:

Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:529
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 22:45:25 (2 occurrences)
Last logged: 22:56:40

[140352280754256] The system cannot restart because the configuration is not valid: Platform error climate.salusfy - No module named 'custom_components.salusfy.climate'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 529, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.salusfy - No module named 'custom_components.salusfy.climate'

**Comment by dragosrds** [comment]
hi, any updates ?  I have a similar error : 
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:528
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:31:42 (1 occurrences)
Last logged: 12:31:42

[140273637015024] The system cannot restart because the configuration is not valid: Platform error climate.salusfy - Integration 'salusfy' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 528, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error climate.salusfy - Integration 'salusfy' not found.


Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:517
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 12:31:42 (1 occurrences)
Last logged: 12:31:42

The system cannot restart because the configuration is not valid: Platform error climate.salusfy - Integration 'salusfy' not found.

**Comment by mariandodu** [comment]
Similar error : The system cannot restart because the configuration is not valid: Platform error climate.salusfy - Integration 'salusfy' not found.

**Comment by gmoscalu** [comment]
Just found this integration and got it up & running in about 30 min...

In order to get this working:
* copied the custom_components folder in place
* restarted HA (so it reads the custom component, even if not in use)
* added the code to the "configuration.yaml" file
* restarted HA again. After a short while, the entity appeared & was able to add the Thermostat card to my dashboard...

Since i had a 2nd Salus device on my account (electric water heater, while first device controls the gas-heater), i did the following:
* copy the "config\custom_components\salusfy" folder to "config\custom_components\salusfy-el"
* quick edit of the "manifest.json" - update the "domain" and "name"
* change the variable name in lines 78 & 82: "SalusThermostat" => "SalusThermostat2"
* restart HA (to read new add-on)
* add lines with login credentials and new device ID to "configuration.yaml" file
* Restart HA again => now i have both devices in

I's appreciate if we can see the water heating icon too...
