### ISSUE TITLE
Thermostat stuck at 32degrees when connection to Salus lost

### ISSUE THREAD

**Issue by 8illy8o8** [floringhimie/salusfy#9]
Each time the log files in HA show that the data connection to Salus gets lost the thermostat moves to 32degrees.
It may return to normal once or twice but at some point gets stuck permanently at 32 until HA is restarted.

Is there a way of keeping it at last known value until data is restored?

![image](https://github.com/floringhimie/salusfy/assets/63656681/2d18338b-b7b2-4258-b78a-3d24425f7887)
![image](https://github.com/floringhimie/salusfy/assets/63656681/214abfca-870b-4605-a573-7bd0f003a728)

This error originated from a custom integration.

Logger: custom_components.salusfy.climate
Source: custom_components/salusfy/climate.py:271
Integration: salusfy (documentation, issues)
First occurred: December 3, 2023 at 5:53:44 PM (1 occurrences)
Last logged: December 3, 2023 at 5:53:44 PM

Error Geting the data from Web. Please check the connection to salus-it500.com manually.

**Comment by snigehere** [comment]
Yes.. i saw the sane issue last week and had to do a restart . As I am just starting to use ha to manage my heating I added an automation to flag an alert to my phone if happens so I can annually fix it

**Comment by dz0ltan** [comment]
Thanks for the tip!

I will also do that.

**Comment by floringhimie** [comment]
have you check it after this MR? https://github.com/floringhimie/salusfy/pull/11

**Comment by Claudio1L** [comment]
Just updated, I receive the following:

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:361
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 15:32:55 (1 occurrences)
Last logged: 15:32:55
Error while setting up salusfy platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/salusfy/climate.py", line 78, in async_setup_platform
    await async_setup_reload_service(hass, DOMAIN, PLATFORMS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'async_setup_reload_service' is not defined

**Comment by mrEnigmator** [comment]
@8illy8o8 Did you manage to solve this problem?

**Comment by 8illy8o8** [comment]
Yes I fixed it by getting rid of the Salus kit entirely. I hadn't realised how simple it was to replace with a Sonoff relay and a few cheap ZigBee temperature sensors. I have them dotted around the house and have the average temperature controlling a HA thermostat. It works beautifully and I no longer have to put up with the shortcomings of the Salus. Wish I had done it sooner.
